name: dropzy-web
services:
  - name: web
    type: static_site
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    output_dir: dist
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
