# DigitalOcean App Platform Spec
# Bu dosya DigitalOcean'da otomatik deployment için gerekli

name: dropship-automation
region: fra  # Frankfurt (Türkiye'ye en yakın)

services:
- name: api
  github:
    repo: USERNAME/REPO_NAME  # GitHub kullanıcı adı ve repo adını değiştir
    branch: main
    deploy_on_push: true  # Git push otomatik deploy
  
  source_dir: /dropship_app
  
  # Build settings
  build_command: |
    pip install --upgrade pip
    pip install -r requirements.txt
  
  # Run settings
  run_command: python -m uvicorn api:app --host 0.0.0.0 --port 8080
  
  # Environment variables
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: JWT_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: ENVIRONMENT
    value: production
  - key: DEBUG
    value: "false"
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: PORT
    value: "8080"
  
  # Health check
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  
  # Instance specs
  instance_count: 1
  instance_size_slug: basic-xxs  # $5/mo - 512MB RAM, 1 vCPU
  
  # HTTP settings
  http_port: 8080
  
  # Routes
  routes:
  - path: /
  
  # CORS
  cors:
    allow_origins:
    - regex: .*
    allow_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    allow_headers:
    - Content-Type
    - Authorization
    - X-Requested-With

# Database
databases:
- name: dropship-db
  engine: PG  # PostgreSQL
  version: "15"
  production: true
  cluster_name: dropship-db-cluster
  db_name: dropship_production
  db_user: dropship_user

# Domain (opsiyonel - custom domain için)
# domains:
# - domain: yourdomain.com
#   type: PRIMARY
#   zone: yourdomain.com

# Features
features:
- buildpack-stack=ubuntu-22

# Alerts (opsiyonel)
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
